@startuml
class Alumno {
- nombre : String
- apellido : String
- legajo : String
}
class Parcial {
- unidad :int
- reintentosRealizados : int
+ sePuedeRecuperar() : boolean
}
class Final {
-  notaOral : double
-  descripcion : String
+  estaAprobado() : boolean
}
abstract class Examen {
- {static} NOTA_MINIMA :int
- alumno : Alumno
- titulo : String
- enunciado : String
- nota : double
+  getNota() : double
+ estaAprobado(): boolean
}

interface Comparable{
+compareTo((Object 0) : int
}

Examen <|-- Parcial
Comparable <|.. Final
Examen <|-- Final
Alumno o-- Examen
@enduml